{{- $endpoint := required "endpoint is required" .Values.endpoint -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: cilium-k8s-service-host
  namespace: kube-system
data:
  host: {{ $endpoint | trimPrefix "https://" | quote }}
